scoreboard objectives add posx dummy
scoreboard objectives add posy dummy
scoreboard objectives add posz dummy
scoreboard objectives add rotx dummy
scoreboard objectives add roty dummy
scoreboard objectives add velocity dummy
scoreboard objectives add velocityX dummy
scoreboard objectives add velocityY dummy
scoreboard objectives add velocityZ dummy
scoreboard objectives add hunger dummy
scoreboard objectives add saturation dummy
scoreboard objectives add absorption dummy
scoreboard objectives add armor dummy
scoreboard objectives add selected_slot dummy
scoreboard objectives add respawnPosX dummy
scoreboard objectives add respawnPosY dummy
scoreboard objectives add respawnPosZ dummy
scoreboard objectives add tps dummy
scoreboard objectives add killcount dummy
scoreboard objectives add mobkillcount dummy
scoreboard objectives add destroyPosX dummy
scoreboard objectives add destroyPosY dummy
scoreboard objectives add destroyPosZ dummy
scoreboard objectives add Lcps dummy
scoreboard objectives add jump_power dummy
scoreboard objectives add Rcps dummy
scoreboard objectives add FPS dummy
scoreboard objectives add health_max dummy
scoreboard objectives add health dummy
scoreboard objectives add damage_taken dummy
scoreboard objectives add on_damage dummy
scoreboard objectives add hit dummy
scoreboard objectives add JumpPower dummy
scoreboard objectives add this_ping dummy
scoreboard objectives add chat_speed dummy
scoreboard objectives add damage_value dummy